export const ADD = 'ADD';
export const REMOVE = 'REMOVE';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const ORDER_SUCCEED = 'ORDER_SUCCEED';
export const ORDER_FAILED = 'ORDER_FAILED';
export const ORDER_LOADING = 'ORDER_LOADING';
export const ORDER_SUCCESS_REDIRECT = 'ORDER_SUCCESS_REDIRECT';
export const GET_ORDERS = 'GET_ORDERS';
export const RESET_BURGER = 'RESET_BURGER';
export const GET_ORDERS_START = 'GET_ORDERS_START';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';
export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';
export const DELETE_ORDER_START = 'DELETE_ORDER_START';
export const VIEW_ORDER_START = 'VIEW_ORDER_START';
export const VIEW_ORDER = 'VIEW_ORDER';
export const SWITCH_REDIRECT_TO_FALSE = 'SWITCH_REDIRECT_TO_FALSE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

